version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
     - db:db
    ports:
      - "8081:80"

  omeka-s:
    depends_on:
      - db
    build: ./
    image: klokantech/omeka-s
    ports:
      - "8080:80"
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/custom/:/var/www/html/themes/custom/
    restart: always

